### ISSUE TITLE
Electron instances not destroyed

### ISSUE THREAD

**Issue by AaronTrazona** [segmentio/nightmare#688]
I already called .end() function somehow there is a electron still running in the task.
Anyone has a great idea how can i solve this issue? This issue bothering almost 1 month I can't find any solution.

Thanks

**Comment by rosshinkley** [comment]
Could you post a small example that reproduces the problem?

**Comment by AaronTrazona** [comment]
Basically, what I did make a lot of instances of nightmare until the nightmare stuck up when I stopped the process the electron still running in background even though I already stopped the process.

**Comment by mashaalmemon** [comment]
@AaronTrazona or @rosshinkley, it has been about a month since there was activity on this thread. ny further headway made on this? On my end, I have electron processes hanging around when my app is idle and nightmare.end() has been called. 

Was any route cause or solution found?

**Comment by TimNZ** [comment]
Nightmare is killing the main process it launches via child_process.spawn, and intermittently renderer processes are being orphaned after the kill()

I have a script that runs periodically purging abandoned electron.exe processes as I have a long running service based app using nightmare.

It is fairly easily re-produceable.  I've had it happen even just launch electron.exe manually and then killing the main process.

It may be worth having end() send a message to the spawned Electron process asking it to kill itself via app.quit() to see if that makes a difference.

If I get time next week I'll create a simple test app that can reproduce it.

**Comment by mashaalmemon** [comment]
@TimNZ that makes a whole lot of sense. I've experienced this on MacOSX as well as on linux (specifically running in a docker instance so the flavour of linux is the one that the official "node:6.2.2" is based on).

Hopefully there is a solution that can be used cross platform. I am attempting to use nightmare in a production environment but can't until this problem is solved.

**Comment by rosshinkley** [comment]
@TimNZ If I'm understanding the problem properly (and it is _thoroughly_ possible I am not), this would mean either that `ChildProcess.kill()` isn't actually killing the child process, meaning Electron isn't honoring `SIGTERM`, or there is some edge case for ending the process that isn't handled properly.  (The latter seems _far_ more likely.)

I am curious to see a reproduction - that would be most informative.

**Comment by TimNZ** [comment]
Ross, details here: https://github.com/electron/electron/issues/6120

It's orphaned Renderer/Helper processes, not Main.

As I said I don't think it is a Nightmare issue, and at this stage think it may have only been happening on Windows.

I haven't investigated further either since about Electron 1.2.3 since the app I deployed runs just fine in conjunction with an hourly script to kill orphaned renderer processes.

I'll try to do a mini app next week to replicate, and see if it getting the runner process to do app.quit() makes any difference.

**Comment by voidmonk** [comment]
In my testing as well, I've noticed that if Nightmare is run in a service/daemon or HTTP server, Electron instances aren't killed by `nightmare.end()`. One workaround that works, is to disconnect & kill the child process explicitly (see code below):

```node
.then(function(result) {
  // process the result
})
.catch(function(err) {
  // handle any error
})
.then(_ => {
  // finally cleanup
  nightmare.end();
  // kill the Electron process explicitly to ensure no orphan child processes
  nightmare.proc.disconnect();
  nightmare.proc.kill();
  nightmare.ended = true;
  nightmare = null;
});
```

**Comment by daniel3d** [comment]
Do you have example app to be tested the #757 maybe have fixed the issue.

**Comment by rafalneves** [comment]
This issue was not fixed by #575.

**Comment by daniel3d** [comment]
@rafalneves Can you give more info your comment is not really constructive what did you test what is not fixed?

**Comment by rafalneves** [comment]
I just replied to the previous comment. I tried to run the latest code (that includes #757 commited code) and I run into same problem. Right now I'm using the fix proposed by @voidmonk that solved the issue.

I was using debian 8. Was an sporadic need, so I didn't test it anywhere else.
If I can assist you more, let me know.

**Comment by itomas** [comment]
I have figured out this bug in my code, but do not know exactly why. 
Electron instances is not destroyed in this example:
`function get(url, options) {
  return new Promise((resolve, reject) => {
    new Nightmare({
      show: false,
      executionTimeout: 15000,
      gotoTimeout: 10000
    })
      .goto(url)
      .pdf(null, options, function (err, buffer) {
        if (err) {
          reject(err);
          return;
        }
        resolve(buffer);
        return true;
      })
      .end();
  });
}`

Here is working example:
`function get(url, options) {
  return new Promise((resolve, reject) => {
    const nightmare = new Nightmare({
      show: false,
      executionTimeout: 15000,
      gotoTimeout: 10000
    });

    const buffer = nightmare
      .goto(url)
      .pdf(null, options)
      .end();

    resolve(buffer);
  });
}`

**Comment by daniel3d** [comment]
@itomas i'm unable to reproduce the issue

>  Electron instances is not destroyed 

after executing the script you provided. Electron is closed correctly only thing I had to do to make it run was to add `.then()` otherwise the script is not working try running this on your machine and let me know if you still experiencing the same issue.

```javascript
var Nightmare = require('nightmare');

function get(url, options) {
  const nightmare = new Nightmare({
    show: false,
    executionTimeout: 15000,
    gotoTimeout: 10000
  });

  return nightmare
    .goto(url)
    .pdf('print.pdf', options)
    .end()
    // i had to add this to get it working
    //-----------------------------------------------------
    .then(function (result) {})
    .catch(function (error) { console.error(error); });
}

get('http://yahoo.com')
```

`os` Microsoft Windows [Version 6.3.9600]
`node` 6.9.1
`electron` 1.3.2
`nightmare`  2.9.0

> Note that if you're using promises, `.then()` must be called after `.end()`
[check the above here](https://github.com/segmentio/nightmare#end)

**Comment by casesandberg** [comment]
Are you still having trouble and have you tried 2.10.0? I am going to close this, but feel free to re-open if it's still an issue.

**Comment by fluky** [comment]
I'm still seeing this on OSX with 2.10.0.

**Comment by Caperious** [comment]
What about if we are using nightmare with async await?

```
let nightmare = new Nightmare(NightmareOption);
let html: any;
let result: any = await nightmare
    .useragent('chrome')
    .goto(url);
html = await nightmare.evaluate(() => {
    return document.querySelector('body').innerHTML;
})
    .end();
```
